name: "Provision AKS cluster"
on:
  workflow_dispatch:
  
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "./aks"
          tf_actions_comment: true

      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "./aks"
          tf_actions_comment: true
        env:
          ARM_CLIENT_ID: ${{ secrets.TF_VAR_agent_client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_agent_client_secret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
          ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}

      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "./aks"
          tf_actions_comment: true
        env:
          ARM_CLIENT_ID: ${{ secrets.TF_VAR_agent_client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_agent_client_secret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
          ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "./aks"
          tf_actions_comment: true
        env:
          ARM_CLIENT_ID: ${{ secrets.TF_VAR_agent_client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_agent_client_secret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
          ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}

      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "./aks"
          tf_actions_comment: true
        env:
          ARM_CLIENT_ID: ${{ secrets.TF_VAR_agent_client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_agent_client_secret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
          ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}